import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Layout from "@/components/layout/Layout";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster as INT } from "sonner"; // Internal notification
import { Toaster as ENT } from "react-hot-toast"; // External notification

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang='en'>
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#1E1F25] text-white min-h-screen w-full`}
        >
          {children}
          <INT richColors expand={true} />
          <ENT position='top-right' toastOptions={{ duration: 5000 }} />
        </body>
      </AuthProvider>
    </html>
  );
}
